server:
  port: ${PORT:0}

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://172.20.0.2:3306/appointment_user?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  application:
    name: user-ws
  flyway:
    user: root
    password: admin
    schemas: public
    url: jdbc:mysql://172.20.0.2:3306/appointment_user
    locations: classpath:migrations
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}

userservice:
  secret: secret123456789secret

logging:
  level:
    com:
      appoitment:
        userservice:
          service:
            thirdparty:
              appointmentService:
                AppointmentFeignClient: debug