server:
  port: ${PORT:0}

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/AppointmentsUserService?createDatabaseIfNotExist=true
    username: root
    password: Armin#123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  application:
    name: user-ws
  flyway:
    user: root
    password: Armin#123
    schemas: public
    url: jdbc:mysql://localhost:3306/AppointmentsUserService
    locations: classpath:migrations
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}