server:
  port: ${PORT:0}

spring:
  web:
    resources:
      add-mappings: false
  application:
    name: appointment-ws
  datasource:
    url: jdbc:mysql://172.20.0.2:3306/appointments?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        driverClassName:
          com.mysql.cj.jdbc.Driver
        dialect:
          org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  data:
    mongodb:
      host: 172.21.0.3
      port: 27017
      database: appointments
      username: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
